Added Euler problems 19, 20, 21, 23, 24
freeCodeCamp/arcade-mode pull request #36
Opened 2017-10-21 14:25 UTC by elliotjz

2017-11-14 01:39 UTC, alvinkl commented on client/scripts/challenges/projecteuler/formatted/001_to_100/Problem 019: Counting Sundays.js
> +/// <p class="euler__paragraph">And on leap years, twenty-nine.</p>
I think it's better to use bullet points like in https://projecteuler.net/problem=19
so it's more readable.

2017-11-14 01:50 UTC, alvinkl requested changes

2017-11-14 01:50 UTC, alvinkl commented on client/scripts/challenges/projecteuler/formatted/001_to_100/Problem 019: Counting Sundays.js
> +/// <p class="euler__paragraph">And on leap years, twenty-nine.</p>
I think it's better to use bullet points like in https://projecteuler.net/problem=19
so it's more readable.

2017-11-17 09:11 UTC, elliotjz commented
This HTML formatting will only work after pull request #42 is merged.

2017-11-27 10:50 UTC, merged